server:
  port: 9001


eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defalutZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: ZH-EUREKA-ORDER

feign:
  hystrix:
    enabled: true